mysql:
  image: library/mysql:5.6
  ports:
  # do not expose the default port cause it's already used on travis: https://github.com/travis-ci/travis-ci/issues/7008
    - "3307:3306"
  environment:
      - "MYSQL_ROOT_PASSWORD=password"
sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"