sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
dynamodb:
  image: peopleperhour/dynamodb
  ports:
    - "45678:8000"
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"
